-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("CTRL + XF86AudioLowerVolume")
hl.bind("CTRL + XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call mpris decrement 5"), { locked = true, repeating = true, description = "dms ipc call mpris decrement 5" })
hl.unbind("CTRL + XF86AudioRaiseVolume")
hl.bind("CTRL + XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call mpris increment 5"), { locked = true, repeating = true, description = "dms ipc call mpris increment 5" })
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), { locked = true, repeating = true, description = "dms ipc call audio decrement 5" })
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), { locked = true, repeating = true, description = "dms ipc call audio increment 5" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("kitty fish -c yazi"), { description = "yazi" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
